name: Publish to npm

on:
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    deploy:
        name: Publish to npm
        runs-on: ubuntu-latest
        environment:
            name: npm

        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  persist-credentials: false

            - name: Publish to npm
              run: npm publish --provenance --access public
